Models/ErrorViewModel.cs
namespace Educacion.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Estudiante.cs
using System.ComponentModel.DataAnnotations;
namespace Educacion.Models
{
    public class Estudiante
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public string? ApellidoP { get; set; }
        public string? ApellidoM { get; set; }
        public string? Grado { get; set; }
        public int Edad { get; set; }
        public int TelefonoTutor { get; set; }



        [DataType(DataType.Date)]
        public DateTime FechaInscripcion { get; set; }
    }
}

Controllers/EstudiantesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Educacion.Data;
using Educacion.Models;

namespace Educacion.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly EducacionContext _context;

        public EstudiantesController(EducacionContext context)
        {
            _context = context;
        }

        // GET: Estudiantes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Estudiante.ToListAsync());
        }

        // GET: Estudiantes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiante
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // GET: Estudiantes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estudiantes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,ApellidoP,ApellidoM,Grado,Edad,TelefonoTutor,FechaInscripcion")] Estudiante estudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudiante);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiante.FindAsync(id);
            if (estudiante == null)
            {
                return NotFound();
            }
            return View(estudiante);
        }

        // POST: Estudiantes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,ApellidoP,ApellidoM,Grado,Edad,TelefonoTutor,FechaInscripcion")] Estudiante estudiante)
        {
            if (id != estudiante.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudiante);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudianteExists(estudiante.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estudiante);
        }

        // GET: Estudiantes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var estudiante = await _context.Estudiante
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estudiante == null)
            {
                return NotFound();
            }

            return View(estudiante);
        }

        // POST: Estudiantes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var estudiante = await _context.Estudiante.FindAsync(id);
            _context.Estudiante.Remove(estudiante);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudianteExists(int id)
        {
            return _context.Estudiante.Any(e => e.Id == id);
        }
    }
}

Controllers/HelloWorldController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;

namespace MvcMovie.Controllers
{
    public class HelloWorldController : Controller
    {
        // 
        // GET: /HelloWorld/

        public IActionResult Index()
        {
            return View();
        }

        // 
        // GET: /HelloWorld/Welcome/ 

        // Requires using System.Text.Encodings.Web;
        public IActionResult Welcome(string name, int numTimes = 1)
        {
            ViewData["Message"] = "Hello " + name;
            ViewData["NumTimes"] = numTimes;

            return View();
        }
    }
}

Controllers/HomeController.cs
using Educacion.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Educacion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Estudiantes/Create.cshtml
@model Educacion.Models.Estudiante

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Estudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoP" class="control-label"></label>
                <input asp-for="ApellidoP" class="form-control" />
                <span asp-validation-for="ApellidoP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoM" class="control-label"></label>
                <input asp-for="ApellidoM" class="form-control" />
                <span asp-validation-for="ApellidoM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grado" class="control-label"></label>
                <input asp-for="Grado" class="form-control" />
                <span asp-validation-for="Grado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoTutor" class="control-label"></label>
                <input asp-for="TelefonoTutor" class="form-control" />
                <span asp-validation-for="TelefonoTutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInscripcion" class="control-label"></label>
                <input asp-for="FechaInscripcion" class="form-control" />
                <span asp-validation-for="FechaInscripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudiantes/Delete.cshtml
@model Educacion.Models.Estudiante

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Estudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoTutor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoTutor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInscripcion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Estudiantes/Details.cshtml
@model Educacion.Models.Estudiante

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Estudiante</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoP)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TelefonoTutor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TelefonoTutor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaInscripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaInscripcion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Estudiantes/Edit.cshtml
@model Educacion.Models.Estudiante

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Estudiante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoP" class="control-label"></label>
                <input asp-for="ApellidoP" class="form-control" />
                <span asp-validation-for="ApellidoP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoM" class="control-label"></label>
                <input asp-for="ApellidoM" class="form-control" />
                <span asp-validation-for="ApellidoM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grado" class="control-label"></label>
                <input asp-for="Grado" class="form-control" />
                <span asp-validation-for="Grado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelefonoTutor" class="control-label"></label>
                <input asp-for="TelefonoTutor" class="form-control" />
                <span asp-validation-for="TelefonoTutor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaInscripcion" class="control-label"></label>
                <input asp-for="FechaInscripcion" class="form-control" />
                <span asp-validation-for="FechaInscripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudiantes/Index.cshtml
@model IEnumerable<Educacion.Models.Estudiante>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Grado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelefonoTutor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInscripcion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelefonoTutor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInscripcion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/HelloWorld/Index.cshtml
@{
    ViewData["Title"] = "Movie List";
}

<h2>My Movie List</h2>

<p>Hello from our View Template!</p>

Views/HelloWorld/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<h2>Welcome</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]!; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Educacion app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Educacion.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Estudiantes" asp-action="Index">Educacion app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Educacion app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>